const fakeDrawings = [
    { id: "1", name: "Drawing 1", theme: "Bateau", url: "/images/picture.jpg" },
    {
        id: "2",
        name: "Drawing 2",
        theme: "Action",
        url: "/images/picture2.png",
    },
    { id: "3", name: "Drawing 3", theme: "Pêche", url: "/images/picture.jpg" },
    {
        id: "4",
        name: "Drawing 4",
        theme: "Passion",
        url: "/images/picture.jpg",
    },
    { id: "5", name: "Drawing 5", theme: "Bateau", url: "/images/picture.jpg" },
    {
        id: "6",
        name: "Drawing 6",
        theme: "Action",
        url: "/images/picture2.png",
    },
    { id: "7", name: "Drawing 7", theme: "Pêche", url: "/images/picture.jpg" },
    {
        id: "8",
        name: "Drawing 8",
        theme: "Passion",
        url: "/images/picture2.png",
    },
    { id: "9", name: "Drawing 9", theme: "Bateau", url: "/images/picture.jpg" },
    {
        id: "10",
        name: "Drawing 10",
        theme: "Action",
        url: "/images/picture2.png",
    },
    {
        id: "11",
        name: "Drawing 11",
        theme: "Pêche",
        url: "/images/picture.jpg",
    },
    {
        id: "12",
        name: "Drawing 12",
        theme: "Passion",
        url: "/images/picture2.png",
    },
    {
        id: "13",
        name: "Drawing 13",
        theme: "Bateau",
        url: "/images/picture.jpg",
    },
    {
        id: "14",
        name: "Drawing 14",
        theme: "Action",
        url: "/images/picture2.png",
    },
    {
        id: "15",
        name: "Drawing 15",
        theme: "Pêche",
        url: "/images/picture.jpg",
    },
    {
        id: "16",
        name: "Drawing 16",
        theme: "Passion",
        url: "/images/picture2.png",
    },
    {
        id: "17",
        name: "Drawing 17",
        theme: "Bateau",
        url: "/images/picture.jpg",
    },
    {
        id: "18",
        name: "Drawing 18",
        theme: "Action",
        url: "/images/picture2.png",
    },
    {
        id: "19",
        name: "Drawing 19",
        theme: "Pêche",
        url: "/images/picture.jpg",
    },
    {
        id: "20",
        name: "Drawing 20",
        theme: "Passion",
        url: "/images/picture2.png",
    },
    {
        id: "21",
        name: "Drawing 21",
        theme: "Bateau",
        url: "/images/picture.jpg",
    },
    {
        id: "22",
        name: "Drawing 22",
        theme: "Action",
        url: "/images/picture2.png",
    },
    {
        id: "23",
        name: "Drawing 23",
        theme: "Pêche",
        url: "/images/picture.jpg",
    },
    {
        id: "24",
        name: "Drawing 24",
        theme: "Passion",
        url: "/images/picture2.png",
    },
    {
        id: "25",
        name: "Drawing 25",
        theme: "Bateau",
        url: "/images/picture.jpg",
    },
    {
        id: "26",
        name: "Drawing 26",
        theme: "Action",
        url: "/images/picture2.png",
    },
    {
        id: "27",
        name: "Drawing 27",
        theme: "Pêche",
        url: "/images/picture.jpg",
    },
    {
        id: "28",
        name: "Drawing 28",
        theme: "Passion",
        url: "/images/picture2.png",
    },
    {
        id: "29",
        name: "Drawing 29",
        theme: "Bateau",
        url: "/images/picture.jpg",
    },
    {
        id: "30",
        name: "Drawing 30",
        theme: "Action",
        url: "/images/picture2.png",
    },
    {
        id: "31",
        name: "Drawing 31",
        theme: "Pêche",
        url: "/images/picture.jpg",
    },
    {
        id: "32",
        name: "Drawing 32",
        theme: "Passion",
        url: "/images/picture2.png",
    },
    {
        id: "33",
        name: "Drawing 33",
        theme: "Bateau",
        url: "/images/picture.jpg",
    },
    {
        id: "34",
        name: "Drawing 34",
        theme: "Action",
        url: "/images/picture2.png",
    },
    {
        id: "35",
        name: "Drawing 35",
        theme: "Pêche",
        url: "/images/picture.jpg",
    },
    {
        id: "36",
        name: "Drawing 36",
        theme: "Passion",
        url: "/images/picture2.png",
    },
    {
        id: "37",
        name: "Drawing 37",
        theme: "Bateau",
        url: "/images/picture.jpg",
    },
    {
        id: "38",
        name: "Drawing 38",
        theme: "Action",
        url: "/images/picture2.png",
    },
    {
        id: "39",
        name: "Drawing 39",
        theme: "Pêche",
        url: "/images/picture.jpg",
    },
    {
        id: "40",
        name: "Drawing 40",
        theme: "Passion",
        url: "/images/picture2.png",
    },
    {
        id: "41",
        name: "Drawing 41",
        theme: "Bateau",
        url: "/images/picture3.png",
    },
    {
        id: "42",
        name: "Drawing 42",
        theme: "Action",
        url: "/images/picture2.png",
    },
    {
        id: "43",
        name: "Drawing 43",
        theme: "Pêche",
        url: "/images/picture3.png",
    },
    {
        id: "44",
        name: "Drawing 44",
        theme: "Passion",
        url: "/images/picture2.png",
    },
    {
        id: "45",
        name: "Drawing 45",
        theme: "Bateau",
        url: "/images/picture3.png",
    },
    {
        id: "46",
        name: "Drawing 46",
        theme: "Action",
        url: "/images/picture.jpg",
    },
    {
        id: "47",
        name: "Drawing 47",
        theme: "Pêche",
        url: "/images/picture.jpg",
    },
    {
        id: "48",
        name: "Drawing 48",
        theme: "Passion",
        url: "/images/picture.jpg",
    },
    {
        id: "49",
        name: "Drawing 49",
        theme: "Bateau",
        url: "/images/picture.jpg",
    },
    {
        id: "50",
        name: "Drawing 50",
        theme: "Action",
        url: "/images/picture.jpg",
    },
    {
        id: "51",
        name: "Drawing 51",
        theme: "Pêche",
        url: "/images/picture.jpg",
    },
    {
        id: "52",
        name: "Drawing 52",
        theme: "Passion",
        url: "/images/picture.jpg",
    },
    {
        id: "53",
        name: "Drawing 53",
        theme: "Bateau",
        url: "/images/picture.jpg",
    },
    {
        id: "54",
        name: "Drawing 54",
        theme: "Action",
        url: "/images/picture.jpg",
    },
    {
        id: "55",
        name: "Drawing 55",
        theme: "Pêche",
        url: "/images/picture.jpg",
    },
    {
        id: "56",
        name: "Drawing 56",
        theme: "Passion",
        url: "/images/picture.jpg",
    },
    {
        id: "57",
        name: "Drawing 57",
        theme: "Bateau",
        url: "/images/picture.jpg",
    },
    {
        id: "58",
        name: "Drawing 58",
        theme: "Action",
        url: "/images/picture.jpg",
    },
    {
        id: "59",
        name: "Drawing 59",
        theme: "Pêche",
        url: "/images/picture.jpg",
    },
    {
        id: "60",
        name: "Drawing 60",
        theme: "Passion",
        url: "/images/picture.jpg",
    },
    {
        id: "61",
        name: "Drawing 61",
        theme: "Bateau",
        url: "/images/picture.jpg",
    },
    {
        id: "62",
        name: "Drawing 62",
        theme: "Action",
        url: "/images/picture.jpg",
    },
    {
        id: "63",
        name: "Drawing 63",
        theme: "Avion",
        url: "/images/picture.jpg",
    },
    {
        id: "64",
        name: "Drawing 64",
        theme: "Emotion",
        url: "/images/picture.jpg",
    },
    {
        id: "65",
        name: "Drawing 65",
        theme: "Cartable",
        url: "/images/picture3.png",
    },
    {
        id: "66",
        name: "Drawing 66",
        theme: "Avion",
        url: "/images/picture.jpg",
    },
    {
        id: "67",
        name: "Drawing 67",
        theme: "Emotion",
        url: "/images/picture3.png",
    },
    {
        id: "68",
        name: "Drawing 68",
        theme: "Cartable",
        url: "/images/picture.jpg",
    },
    {
        id: "69",
        name: "Drawing 69",
        theme: "Avion",
        url: "/images/picture.jpg",
    },
    {
        id: "70",
        name: "Drawing 70",
        theme: "Emotion",
        url: "/images/picture3.png",
    },
    {
        id: "71",
        name: "Drawing 71",
        theme: "Cartable",
        url: "/images/picture.jpg",
    },
    {
        id: "72",
        name: "Drawing 72",
        theme: "Avion",
        url: "/images/picture.jpg",
    },
    {
        id: "73",
        name: "Drawing 73",
        theme: "Emotion",
        url: "/images/picture3.png",
    },
    {
        id: "74",
        name: "Drawing 74",
        theme: "Cartable",
        url: "/images/picture3.png",
    },
    {
        id: "75",
        name: "Drawing 75",
        theme: "Avion",
        url: "/images/picture3.png",
    },
    {
        id: "76",
        name: "Drawing 76",
        theme: "Emotion",
        url: "/images/picture3.png",
    },
    {
        id: "77",
        name: "Drawing 77",
        theme: "Cartable",
        url: "/images/picture.jpg",
    },
    {
        id: "78",
        name: "Drawing 78",
        theme: "Avion",
        url: "/images/picture.jpg",
    },
    {
        id: "79",
        name: "Drawing 79",
        theme: "Emotion",
        url: "/images/picture.jpg",
    },
    {
        id: "80",
        name: "Drawing 80",
        theme: "Cartable",
        url: "/images/picture3.png",
    },
    {
        id: "81",
        name: "Drawing 81",
        theme: "Avion",
        url: "/images/picture3.png",
    },
    {
        id: "82",
        name: "Drawing 82",
        theme: "Emotion",
        url: "/images/picture3.png",
    },
    {
        id: "83",
        name: "Drawing 83",
        theme: "Cartable",
        url: "/images/picture3.png",
    },
    {
        id: "84",
        name: "Drawing 84",
        theme: "Avion",
        url: "/images/picture.jpg",
    },
    {
        id: "85",
        name: "Drawing 85",
        theme: "Emotion",
        url: "/images/picture.jpg",
    },
    {
        id: "86",
        name: "Drawing 86",
        theme: "Cartable",
        url: "/images/picture.jpg",
    },
    {
        id: "87",
        name: "Drawing 87",
        theme: "Avion",
        url: "/images/picture.jpg",
    },
    {
        id: "88",
        name: "Drawing 88",
        theme: "Emotion",
        url: "/images/picture.jpg",
    },
    {
        id: "89",
        name: "Drawing 89",
        theme: "Cartable",
        url: "/images/picture.jpg",
    },
    {
        id: "90",
        name: "Drawing 90",
        theme: "Avion",
        url: "/images/picture.jpg",
    },
    {
        id: "91",
        name: "Drawing 91",
        theme: "Emotion",
        url: "/images/picture.jpg",
    },
    {
        id: "92",
        name: "Drawing 92",
        theme: "Cartable",
        url: "/images/picture.jpg",
    },
    {
        id: "93",
        name: "Drawing 93",
        theme: "Avion",
        url: "/images/picture.jpg",
    },
    {
        id: "94",
        name: "Drawing 94",
        theme: "Emotion",
        url: "/images/picture.jpg",
    },
    {
        id: "95",
        name: "Drawing 95",
        theme: "Cartable",
        url: "/images/picture.jpg",
    },
    {
        id: "96",
        name: "Drawing 96",
        theme: "Avion",
        url: "/images/picture3.png",
    },
    {
        id: "97",
        name: "Drawing 97",
        theme: "Emotion",
        url: "/images/picture3.png",
    },
    {
        id: "98",
        name: "Drawing 98",
        theme: "Cartable",
        url: "/images/picture3.png",
    },
    {
        id: "99",
        name: "Drawing 99",
        theme: "Avion",
        url: "/images/picture3.png",
    },
];
export default fakeDrawings;
